{% set name = "ABR" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # openssl sha256 ./dist/ABR-{version}.tar.gz (or use `sha256sum`)
  sha256: d83951257bc8cbd0def161f052abc9e0df74b4a98f593f69d313786ed0ec9be3

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - atom
    - enaml
    - matplotlib
    - numpy
    - scipy
    - pandas
    - qt
    - qtpy

test:
  # Some package might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - abr
    - abr.app
    - abr.parsers
  commands:
    - abr
    - abr_gui --threshold-only --demo

about:
  home: http://github.com/bburan/abr
  license: BSD-3-Clause
  license_family: BSD
  summary: 'GUI for analyzing auditory brainstem responses (ABRs)'
  doc_url: http://github.com/bburan/abr
  dev_url: https://github.com/bburan/abr

extra:
  recipe-maintainers:
    - bburan
